services:
  app:
    image: agnesw-project
    platform: linux/amd64
    mem_limit: 4g
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - INPUT_DIR=/data/input
      - OUTPUT_DIR=/data/output
      - S3_BUCKET_NAME=agnesw-project
      - RUN_MODE=local
      - OUTPUT_S3_KEY=output/aiml_info.csv
    volumes:
      - ./data/input:/data/input:ro
      - ./data/output:/data/output
